---
# tasks file for ossec-agent

- name: "Install the correct repository"
  include_tasks: "{{ ansible_os_family }}.yml"
  when: (ossec_disable_public_repos is not defined) or (ossec_disable_public_repos != 'yes')

- name: "Install {{ ossec_agent_package_name }}"
  package:
    name: "{{ ossec_agent_package_name }}"
  when: "'.deb' not in ossec_agent_package_name"

- name: Install OSSEC Agent from .deb package
  apt: deb="{{ ossec_agent_package_name }}"
  when: "'.deb' in ossec_agent_package_name"

- name: Set ossec deploy facts for RedHat
  set_fact:
    ossec_agent_config_filename: ossec-agent.conf
    ossec_init_name: ossec-hids
  when: ansible_os_family == "RedHat"

- name: Set ossec deploy facts for Debian
  set_fact:
    ossec_agent_config_filename: ossec.conf
    ossec_init_name: ossec
  when: ansible_os_family == "Debian"

- name: "Installing the ossec-agent.conf"
  template:
    src: var-ossec-etc-ossec-agent.conf.j2
    dest: /var/ossec/etc/{{ ossec_agent_config_filename }}
    owner: root
    group: root
    mode: 0644
